// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: innerProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "innerProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace rj {
namespace targeting {
namespace protos {

namespace {

const ::google::protobuf::Descriptor* innerProtoEntity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  innerProtoEntity_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* innerProtoEntity_msgType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_innerProto_2eproto() {
  protobuf_AddDesc_innerProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "innerProto.proto");
  GOOGLE_CHECK(file != NULL);
  innerProtoEntity_descriptor_ = file->message_type(0);
  static const int innerProtoEntity_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(innerProtoEntity, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(innerProtoEntity, buf_),
  };
  innerProtoEntity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      innerProtoEntity_descriptor_,
      innerProtoEntity::default_instance_,
      innerProtoEntity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(innerProtoEntity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(innerProtoEntity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(innerProtoEntity));
  innerProtoEntity_msgType_descriptor_ = innerProtoEntity_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_innerProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    innerProtoEntity_descriptor_, &innerProtoEntity::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_innerProto_2eproto() {
  delete innerProtoEntity::default_instance_;
  delete innerProtoEntity_reflection_;
}

void protobuf_AddDesc_innerProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020innerProto.proto\022\027com.rj.targeting.pro"
    "tos\"\201\001\n\020innerProtoEntity\022B\n\007msgtype\030\001 \002("
    "\01621.com.rj.targeting.protos.innerProtoEn"
    "tity.msgType\022\013\n\003buf\030\002 \001(\t\"\034\n\007msgType\022\021\n\r"
    "msg_redisAddr\020\000", 175);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "innerProto.proto", &protobuf_RegisterTypes);
  innerProtoEntity::default_instance_ = new innerProtoEntity();
  innerProtoEntity::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_innerProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_innerProto_2eproto {
  StaticDescriptorInitializer_innerProto_2eproto() {
    protobuf_AddDesc_innerProto_2eproto();
  }
} static_descriptor_initializer_innerProto_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* innerProtoEntity_msgType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return innerProtoEntity_msgType_descriptor_;
}
bool innerProtoEntity_msgType_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const innerProtoEntity_msgType innerProtoEntity::msg_redisAddr;
const innerProtoEntity_msgType innerProtoEntity::msgType_MIN;
const innerProtoEntity_msgType innerProtoEntity::msgType_MAX;
const int innerProtoEntity::msgType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int innerProtoEntity::kMsgtypeFieldNumber;
const int innerProtoEntity::kBufFieldNumber;
#endif  // !_MSC_VER

innerProtoEntity::innerProtoEntity()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void innerProtoEntity::InitAsDefaultInstance() {
}

innerProtoEntity::innerProtoEntity(const innerProtoEntity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void innerProtoEntity::SharedCtor() {
  _cached_size_ = 0;
  msgtype_ = 0;
  buf_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

innerProtoEntity::~innerProtoEntity() {
  SharedDtor();
}

void innerProtoEntity::SharedDtor() {
  if (buf_ != &::google::protobuf::internal::kEmptyString) {
    delete buf_;
  }
  if (this != default_instance_) {
  }
}

void innerProtoEntity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* innerProtoEntity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return innerProtoEntity_descriptor_;
}

const innerProtoEntity& innerProtoEntity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_innerProto_2eproto();
  return *default_instance_;
}

innerProtoEntity* innerProtoEntity::default_instance_ = NULL;

innerProtoEntity* innerProtoEntity::New() const {
  return new innerProtoEntity;
}

void innerProtoEntity::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    msgtype_ = 0;
    if (has_buf()) {
      if (buf_ != &::google::protobuf::internal::kEmptyString) {
        buf_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool innerProtoEntity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .com.rj.targeting.protos.innerProtoEntity.msgType msgtype = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::com::rj::targeting::protos::innerProtoEntity_msgType_IsValid(value)) {
            set_msgtype(static_cast< ::com::rj::targeting::protos::innerProtoEntity_msgType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_buf;
        break;
      }

      // optional string buf = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_buf:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_buf()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->buf().data(), this->buf().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void innerProtoEntity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .com.rj.targeting.protos.innerProtoEntity.msgType msgtype = 1;
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgtype(), output);
  }

  // optional string buf = 2;
  if (has_buf()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->buf().data(), this->buf().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->buf(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* innerProtoEntity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .com.rj.targeting.protos.innerProtoEntity.msgType msgtype = 1;
  if (has_msgtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgtype(), target);
  }

  // optional string buf = 2;
  if (has_buf()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->buf().data(), this->buf().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->buf(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int innerProtoEntity::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .com.rj.targeting.protos.innerProtoEntity.msgType msgtype = 1;
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgtype());
    }

    // optional string buf = 2;
    if (has_buf()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->buf());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void innerProtoEntity::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const innerProtoEntity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const innerProtoEntity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void innerProtoEntity::MergeFrom(const innerProtoEntity& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_buf()) {
      set_buf(from.buf());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void innerProtoEntity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void innerProtoEntity::CopyFrom(const innerProtoEntity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool innerProtoEntity::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void innerProtoEntity::Swap(innerProtoEntity* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(buf_, other->buf_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata innerProtoEntity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = innerProtoEntity_descriptor_;
  metadata.reflection = innerProtoEntity_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace targeting
}  // namespace rj
}  // namespace com

// @@protoc_insertion_point(global_scope)
