// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CommonMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace rj {
namespace protos {
namespace msg {

namespace {

const ::google::protobuf::Descriptor* CommonMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CommonMessage_2eproto() {
  protobuf_AddDesc_CommonMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CommonMessage.proto");
  GOOGLE_CHECK(file != NULL);
  CommonMessage_descriptor_ = file->message_type(0);
  static const int CommonMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonMessage, businesscode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonMessage, datacodingtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonMessage, data_),
  };
  CommonMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonMessage_descriptor_,
      CommonMessage::default_instance_,
      CommonMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CommonMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonMessage_descriptor_, &CommonMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CommonMessage_2eproto() {
  delete CommonMessage::default_instance_;
  delete CommonMessage_reflection_;
}

void protobuf_AddDesc_CommonMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023CommonMessage.proto\022\021com.rj.protos.msg"
    "\"K\n\rCommonMessage\022\024\n\014businessCode\030\001 \002(\t\022"
    "\026\n\016dataCodingType\030\002 \001(\t\022\014\n\004data\030\003 \002(\014", 117);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CommonMessage.proto", &protobuf_RegisterTypes);
  CommonMessage::default_instance_ = new CommonMessage();
  CommonMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CommonMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CommonMessage_2eproto {
  StaticDescriptorInitializer_CommonMessage_2eproto() {
    protobuf_AddDesc_CommonMessage_2eproto();
  }
} static_descriptor_initializer_CommonMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CommonMessage::kBusinessCodeFieldNumber;
const int CommonMessage::kDataCodingTypeFieldNumber;
const int CommonMessage::kDataFieldNumber;
#endif  // !_MSC_VER

CommonMessage::CommonMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CommonMessage::InitAsDefaultInstance() {
}

CommonMessage::CommonMessage(const CommonMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CommonMessage::SharedCtor() {
  _cached_size_ = 0;
  businesscode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  datacodingtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonMessage::~CommonMessage() {
  SharedDtor();
}

void CommonMessage::SharedDtor() {
  if (businesscode_ != &::google::protobuf::internal::kEmptyString) {
    delete businesscode_;
  }
  if (datacodingtype_ != &::google::protobuf::internal::kEmptyString) {
    delete datacodingtype_;
  }
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

void CommonMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonMessage_descriptor_;
}

const CommonMessage& CommonMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonMessage_2eproto();
  return *default_instance_;
}

CommonMessage* CommonMessage::default_instance_ = NULL;

CommonMessage* CommonMessage::New() const {
  return new CommonMessage;
}

void CommonMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_businesscode()) {
      if (businesscode_ != &::google::protobuf::internal::kEmptyString) {
        businesscode_->clear();
      }
    }
    if (has_datacodingtype()) {
      if (datacodingtype_ != &::google::protobuf::internal::kEmptyString) {
        datacodingtype_->clear();
      }
    }
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::kEmptyString) {
        data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string businessCode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_businesscode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->businesscode().data(), this->businesscode().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dataCodingType;
        break;
      }

      // optional string dataCodingType = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dataCodingType:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_datacodingtype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->datacodingtype().data(), this->datacodingtype().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_data;
        break;
      }

      // required bytes data = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CommonMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string businessCode = 1;
  if (has_businesscode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->businesscode().data(), this->businesscode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->businesscode(), output);
  }

  // optional string dataCodingType = 2;
  if (has_datacodingtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->datacodingtype().data(), this->datacodingtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->datacodingtype(), output);
  }

  // required bytes data = 3;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CommonMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string businessCode = 1;
  if (has_businesscode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->businesscode().data(), this->businesscode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->businesscode(), target);
  }

  // optional string dataCodingType = 2;
  if (has_datacodingtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->datacodingtype().data(), this->datacodingtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->datacodingtype(), target);
  }

  // required bytes data = 3;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CommonMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string businessCode = 1;
    if (has_businesscode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->businesscode());
    }

    // optional string dataCodingType = 2;
    if (has_datacodingtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->datacodingtype());
    }

    // required bytes data = 3;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonMessage::MergeFrom(const CommonMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_businesscode()) {
      set_businesscode(from.businesscode());
    }
    if (from.has_datacodingtype()) {
      set_datacodingtype(from.datacodingtype());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonMessage::CopyFrom(const CommonMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;

  return true;
}

void CommonMessage::Swap(CommonMessage* other) {
  if (other != this) {
    std::swap(businesscode_, other->businesscode_);
    std::swap(datacodingtype_, other->datacodingtype_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonMessage_descriptor_;
  metadata.reflection = CommonMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg
}  // namespace protos
}  // namespace rj
}  // namespace com

// @@protoc_insertion_point(global_scope)
